### ISSUE TITLE
Sort out Typescript imports

### ISSUE THREAD

**Issue by alexkcollier** [spartanbio/schedio-tokens#49]
What's the right way to set up the typings, and make them usable in NPM? `*.d.ts` don't seem to be working as intended.

Additionally, the imports are clunky right now and should be improved.

**Comment by nick-mcdonald** [comment]
Maybe this helps
 - https://medium.com/@mweststrate/how-to-create-strongly-typed-npm-modules-1e1bda23a7f4
- https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

The package has a `main`, but no `typings`. Also, I think the .d.ts needs to be in the same directory as the file it is providing types for. So if `dist/react-native/common-js/color.color-map.js` needs it's types in `dist/react-native/common-js/color.color-map.d.ts`. I think there should also be a index.d.ts at the top level for the top level module import to work. That probably isn't necessary.

Ultimately, I think this system has too much flexibility, at least for the react native export 😄 

Probably just need module definitions with the .d.ts in the same directory. I think 🤔
